name: in_app_update_android
description: "A Flutter plugin for Android in-app updates using Google Play's In-App Updates API."
version: 1.0.1
repository: https://github.com/sajedur0/in_app_update_android
homepage: https://github.com/sajedur0/in_app_update_android

environment:
  sdk: ^3.12.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tech.sajedur0.in_app_update_android
        pluginClass: InAppUpdateAndroidPlugin

